### PR TITLE
Smardex: Add integration tests

### PR DESCRIPTION
**Pull request by estebgonza**
This pull requests introduces the integration tests for Smardex adapter.

**Integration tests**:
Network: **Ethereum** 
- Testing the price calculation
 1. For the following pairs: `SDEX/USDT`, `SDEX/WETH`, `SDEX/ETH`.
 2. With multiple amounts
 3. For BUY / SELL directions
 
- Testing the GraphQL query for each configured tokens (ensure there is at least one pool returned that contains more than 0 USD of value)

**Multichain consideration (next step)** 
This scenario will be programmatically re-used for each network with an appropriate configuration of pairs and amounts that we have to test.

### CODE REVIEW

**Comment by estebgonza** [comment]
Let me know @asyx21 about the pairs (SDEX/USDT, SDEX/WETH, SDEX/ETH) and the tested amounts during BUY/SELL actions, if it's ok or not for you :)

**Review by asyx21 — COMMENTED** [review]
Please add WETH/WBTC pair to the test

**Comment by estebgonza** [comment]
> Please add WETH/WBTC pair to the test

Done

**Comment by estebgonza** [comment]
```bash
 PASS  src/dex/smardex/smardex-integration.test.ts (9.242 s)
  Smardex
    Ethereum
      ✓ getTopPoolsForToken (595 ms)
      SDEX <> USDT
        ✓ SELL: Compute pool identiers and prices (791 ms)
        ✓ BUY: Compute pool identiers and prices (727 ms)
      SDEX <> WETH
        ✓ SELL: Compute pool identiers and prices (694 ms)
        ✓ BUY: Compute pool identiers and prices (665 ms)
      SDEX <> ETH
        ✓ SELL: Compute pool identiers and prices (693 ms)
        ✓ BUY: Compute pool identiers and prices (1134 ms)
      WETH <> WBTC
        ✓ SELL: Compute pool identiers and prices (661 ms)
        ✓ BUY: Compute pool identiers and prices (667 ms)

Test Suites: 1 passed, 1 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        9.283 s
``` 

Ouput of integration tests

**Review by asyx21 — APPROVED** [review]

**Pull request merged**
