### PR TITLE
Supports Base on Smardex integration

### PR DESCRIPTION
**Pull request by estebgonza**
I added the configuration of Base contracts for Smardex.

I updated the following tests:
 - end to end
 - integration
 - events

### CODE REVIEW

**Comment by estebgonza** [comment]
All tests are now passing @asyx21 :heavy_check_mark: 
It was a problem of configuration, I didn't correctly defined an address that hold enough SDEX for the simulation on Tenderly.

Fixed in a465463014f4ea88bbf5eb5978e41aa80bdb9fbc

**Comment by estebgonza** [comment]
If you want, you can confirm that the tests are passing on your side too, by running `yarn test-integration smardex`.
With a rpc provider for Base: `HTTP_PROVIDER_8453="..."`.

**Review by asyx21 — COMMENTED** [review]
Base test are passing !
You can PR on main repo once you changed ethereum SDEX holder and verify that ethereum tests are still passing

**Comment by estebgonza** [comment]
> Base test are passing ! You can PR on main repo once you changed ethereum SDEX holder and verify that ethereum tests are still passing

Now it's ok on Ethereum too. The tests are passing correctly with the new address

**Pull request merged**
